### ISSUE TITLE
crime dataset

### ISSUE THREAD

**Issue by SunderlandAJ-1130** [tsinghua-fib-lab/Spatio-temporal-Diffusion-Point-Processes#2]
Dear all, thanks for kindly sharing your codes and datasets. And I am wondering if you could provide further files about the crime dataset you used (i.e., data_train, data_val, data_test). Because I want to implement a more fair comparison. 

If possible, we will cite you where appropriate and mention you in the acknowledgments. Thanks!

**Comment by YuanYuan98** [comment]
Hi, Thanks for your attention. I have provided the crime dataset. It's worth noting that this dataset is unique compared to others because of its discrete characteristics. Unlike other datasets with latitude and longitude coordinates, this dataset uses discrete districts to represent its spatial information. 

You can access the processed crime dataset (data_train, data_val, data_test) by following this link: *[Crime dataset](https://github.com/tsinghua-fib-lab/Spatio-temporal-Diffusion-Point-Processes/tree/main/dataset/Crime)*. The original dataset can be obtained from *[Atlanta 911 calls-for-service data](http://www.atlantapd.org/i-want-to/crime-data-downloads)*.
